# set .env vars: TZ, DOMAIN_NAME , SITE_PATH
#      - WORDPRESS_DATABASE_USER, WORDPRESS_DATABASE_HOST, WORDPRESS_DATABASE_PASSWORD, WORDPRESS_USERNAME
#      - WORDPRESS_PASSWORD, WORDPRESS_EMAIL, WORDPRESS_LANG

version: '3'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    container_name: "mariadb"
    restart: unless-stopped
    environment:
      - TZ
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_USER=${WORDPRESS_DATABASE_USER}
      - MARIADB_PASSWORD=${WORDPRESS_DATABASE_PASSWORD}
      - MARIADB_DATABASE=${SITE_PATH}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD
      interval: 20s
      timeout: 10s
      retries: 10
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks: 
      - mariadb
                        
  webserver:
    image: docker.io/bitnami/wordpress:latest
    container_name: "wp_${SITE_PATH}"
    restart: unless-stopped
    environment:
      - TZ
      - DOMAIN_NAME
      - SITE_PATH
      - PHP_POST_MAX_SIZE
      - PHP_UPLOAD_MAX_FILESIZE
      - PHP_MEMORY_LIMIT=256M
      - WORDPRESS_HOST=${DOMAIN_NAME}/${SITE_PATH}
      - WORDPRESS_SSLPROXY=true
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_NAME=${SITE_PATH}
      - WORDPRESS_DATABASE_USER
      - WORDPRESS_DATABASE_HOST
      - WORDPRESS_DATABASE_PASSWORD
      - WORDPRESS_USERNAME
      - WORDPRESS_PASSWORD
      - WORDPRESS_EMAIL
      - WORDPRESS_LANG
      - WORDPRESS_SKIP_BOOTSTRAP=no
    labels:
      - traefik.enable=true
      - traefik.http.services.wp_${SITE_PATH}.loadbalancer.server.port=8080
      - traefik.http.routers.wp_${SITE_PATH}.tls.certresolver=letsencrypt
      - traefik.frontend.entryPoints=http,https
      - traefik.http.routers.wp_${SITE_PATH}.rule=Host(`${DOMAIN_NAME}`) && ( PathPrefix(`/${SITE_PATH}`) )
    volumes:
      - 'wpdata:/bitnami/wordpress'
    networks: 
      - proxy_default
      - mariadb
    depends_on:
      mariadb:
        condition: service_healthy

  alias:
    image: docker.io/bitnami/wp:4.2
    container_name: "alias_${SITE_PATH}"
    volumes:
      - 'wp_www:/bitnami/wp'
    command: bash -c "sleep 120s ; ln -fs /bitnami/wp/ /bitnami/wp/${SITE_PATH}"
    depends_on:
      - webserver
    

volumes:
  mariadb_data:
  wpdata:
  
networks:
  proxy_default:
    external: true
  mariadb:
